FROM mcr.microsoft.com/dotnet/sdk:8.0 AS server-dev

# Install Paket CLI inside container
RUN dotnet tool install paket --tool-path /usr/local/bin

# All source will be mounted into /workspace
WORKDIR /workspace

ENV ASPNETCORE_ENVIRONMENT=Development

EXPOSE 5000

# Use dotnet watch for HMR; project is at /workspace/Server/Server.fsproj
CMD ["dotnet", "watch", "run" ]
